import { SyllabusChapter } from './types';

export const INITIAL_SYLLABUS: SyllabusChapter[] = [
  // ================= PHYSICS =================
  // Class 11
  {
    id: 'phy-1',
    name: 'Units and Measurements',
    unit: 'Kinematics & Fundamentals',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Dimensions and Dimensional Analysis', 'Significant Figures', 'Errors in Measurement', 'Vernier Calliper & Screw Gauge principles']
  },
  {
    id: 'phy-2',
    name: 'Motion in a Straight Line & Plane',
    unit: 'Kinematics & Fundamentals',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Equations of Motion', 'Relative Velocity', 'Projectile Motion', 'Uniform Circular Motion', 'Vectors and Scalar Components']
  },
  {
    id: 'phy-3',
    name: 'Laws of Motion & Friction',
    unit: 'Mechanics',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ["Newton's Laws", 'Static & Kinetic Friction', 'Banking of Roads', 'Pulley Systems & Free Body Diagrams', 'Linear Momentum Conservation']
  },
  {
    id: 'phy-4',
    name: 'Work, Energy and Power',
    unit: 'Mechanics',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ['Work-Energy Theorem', 'Conservative & Non-Conservative Forces', 'Elastic & Inelastic Collisions', 'Vertical Circular Motion', 'Potential Energy Curves']
  },
  {
    id: 'phy-5',
    name: 'Rotational Motion & Centre of Mass',
    unit: 'Mechanics',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Centre of Mass of 2-Particle & Rigid Systems', 'Moment of Inertia Theorems', 'Torque and Angular Momentum', 'Pure Rolling Motion without Slipping']
  },
  {
    id: 'phy-6',
    name: 'Gravitation',
    unit: 'Mechanics',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ["Kepler's Laws", 'Acceleration due to Gravity with Height/Depth', 'Gravitational Potential Energy & Escape Velocity', 'Orbital Velocity of Satellites']
  },
  {
    id: 'phy-7',
    name: 'Properties of Solids and Fluids',
    unit: 'Properties of Bulk Matter',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ["Hooke's Law & Moduli of Elasticity", "Pascal's Law & Hydrostatic Pressure", "Bernoulli's Theorem & Applications", "Terminal Velocity & Stokes' Law", 'Surface Tension & Capillarity']
  },
  {
    id: 'phy-8',
    name: 'Thermodynamics & Kinetic Theory of Gases',
    unit: 'Thermal Physics',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['First & Second Law of Thermodynamics', 'Isothermal, Adiabatic, Isobaric Processes', 'PV Indicator Diagrams & Work Done', 'Degrees of Freedom & Equipartition of Energy', 'Mean Free Path & RMS Speed']
  },
  {
    id: 'phy-9',
    name: 'Oscillations and Waves',
    unit: 'Vibrations',
    subject: 'Physics',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Simple Harmonic Motion & Energy of SHM', 'Simple Pendulum & Spring-Block Systems', 'Wave Propagation & Speed of Sound', 'Standing Waves in Organ Pipes & Stretched Strings', 'Beats Phenomenon']
  },
  // Class 12
  {
    id: 'phy-10',
    name: 'Electrostatics & Capacitance',
    unit: 'Electromagnetism',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ["Coulomb's Law & Electric Dipole", "Gauss's Theorem and Flux", 'Electrostatic Potential & Equipotential Surfaces', 'Parallel Plate Capacitor & Dielectrics', 'Combination of Capacitors & Energy Stored']
  },
  {
    id: 'phy-11',
    name: 'Current Electricity',
    unit: 'Electromagnetism',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Drift Velocity and Mobility', "Ohm's Law & Temperature Dependence", "Kirchhoff's Laws & Circuit Solving", 'Wheatstone Bridge & Metre Bridge', 'Cells in Series/Parallel and Internal Resistance']
  },
  {
    id: 'phy-12',
    name: 'Magnetic Effects of Current and Magnetism',
    unit: 'Electromagnetism',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Biot-Savart Law & Circular Coils', "Ampere's Circuital Law & Solenoid", 'Lorentz Force on Moving Charges', 'Moving Coil Galvanometer to Ammeter/Voltmeter', 'Magnetic Dipole Moment & Earth Magnetism Elements']
  },
  {
    id: 'phy-13',
    name: 'Electromagnetic Induction & Alternating Current',
    unit: 'Electromagnetism',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ["Faraday's & Lenz's Law of Induction", 'Self & Mutual Inductance', 'Peak vs RMS Voltage & Phase Relations', 'Series LCR Resonance & Quality Factor', 'Power Factor & Transformers']
  },
  {
    id: 'phy-14',
    name: 'Ray and Wave Optics',
    unit: 'Optics',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 5,
    completed: false,
    revisionCount: 0,
    subtopics: ['Refraction at Spherical Surfaces & Lens Maker Formula', 'Prism Dispersion & Minimum Deviation', 'Compound Microscope & Astronomical Telescope', "Huygens' Principle & Wavefronts", "Young's Double Slit Experiment (YDSE) & Fringe Width", 'Diffraction at a Single Slit']
  },
  {
    id: 'phy-15',
    name: 'Modern Physics (Dual Nature, Atoms, Nuclei)',
    unit: 'Modern Physics',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 5,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ["Einstein's Photoelectric Equation & Stopping Potential", "de Broglie Wavelength", "Bohr's Atomic Model & Spectral Lines", 'Nuclear Binding Energy per Nucleon', 'Mass Defect & Q-Value of Nuclear Reactions']
  },
  {
    id: 'phy-16',
    name: 'Semiconductor Electronics',
    unit: 'Modern Physics',
    subject: 'Physics',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Energy Bands in Conductors, Semiconductors, Insulators', 'p-n Junction Diode in Forward & Reverse Bias', 'Half-wave & Full-wave Rectifiers', 'Logic Gates (AND, OR, NOT, NAND, NOR truth tables)']
  },

  // ================= CHEMISTRY =================
  // Class 11
  {
    id: 'chem-1',
    name: 'Some Basic Concepts of Chemistry (Mole Concept)',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ['Mole Concept and Molar Masses', 'Empirical and Molecular Formula', 'Stoichiometry and Limiting Reagent', 'Concentration Terms: Molarity, Molality, Mole Fraction']
  },
  {
    id: 'chem-2',
    name: 'Structure of Atom',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ["Bohr's Model & de Broglie Dual Nature", "Heisenberg's Uncertainty Principle", 'Quantum Numbers (n, l, m, s)', "Aufbau, Pauli's Exclusion, Hund's Rule", 'Shapes of s, p, d Orbitals']
  },
  {
    id: 'chem-3',
    name: 'Classification of Elements and Periodicity',
    unit: 'Inorganic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ['Periodic Trends in Atomic/Ionic Radii', 'Ionization Enthalpy & Electron Gain Enthalpy', 'Electronegativity Trends across Periods & Groups', 'Valency and Anomalous Properties of Second Period Elements']
  },
  {
    id: 'chem-4',
    name: 'Chemical Bonding and Molecular Structure',
    unit: 'Inorganic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Lewis Dot Structures & Formal Charge', 'VSEPR Theory & Molecular Geometry', 'Hybridization (sp, sp2, sp3, sp3d, sp3d2)', 'Molecular Orbital Theory (MOT) & Bond Order', 'Hydrogen Bonding: Inter and Intra']
  },
  {
    id: 'chem-5',
    name: 'Chemical Thermodynamics',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['First Law of Thermodynamics & Enthalpy (ΔH)', "Hess's Law of Constant Heat Summation", 'Entropy (ΔS) and Spontaneity Criterion', "Gibbs Free Energy (ΔG) and Equilibrium Constant", 'Bond Enthalpy Calculations']
  },
  {
    id: 'chem-6',
    name: 'Equilibrium (Chemical & Ionic)',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Law of Mass Action and Kp / Kc relationship', "Le Chatelier's Principle Applications", 'pH Scale and Ionization of Weak Acids/Bases', 'Buffer Solutions (Acidic & Basic Henderson Eq)', 'Solubility Product (Ksp) & Common Ion Effect']
  },
  {
    id: 'chem-7',
    name: 'Redox Reactions',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 1,
    completed: false,
    revisionCount: 0,
    subtopics: ['Oxidation State Calculation Rules', 'Balancing Redox by Ion-Electron Method', 'Types of Redox Reactions', 'Electrochemical Cell Concepts']
  },
  {
    id: 'chem-8',
    name: 'Organic Chemistry: Some Basic Principles & Techniques (GOC)',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['IUPAC Nomenclature of Functional Groups', 'Inductive, Mesomeric (Resonance) & Hyperconjugation', 'Carbocation, Carbanion & Free Radical Stability', 'Electrophiles & Nucleophiles Classification', 'Structural & Stereoisomerism (Geometrical & Optical)']
  },
  {
    id: 'chem-9',
    name: 'Hydrocarbons (Alkanes, Alkenes, Alkynes, Aromatic)',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Free Radical Halogenation of Alkanes', "Markovnikov's & Anti-Markovnikov's Addition to Alkenes", 'Ozonolysis of Alkenes and Alkynes', 'Acidity of Terminal Alkynes', 'Electrophilic Aromatic Substitution (Nitration, Friedel-Crafts)']
  },
  // Class 12
  {
    id: 'chem-10',
    name: 'Solutions',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ["Raoult's Law for Volatile Solutes", 'Ideal vs Non-Ideal Solutions & Azeotropes', 'Colligative Properties (ΔTb, ΔTf, Osmotic Pressure)', "van 't Hoff Factor (i) for Association/Dissociation"]
  },
  {
    id: 'chem-11',
    name: 'Electrochemistry',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Galvanic Cells & Standard Electrode Potentials', 'Nernst Equation and Equilibrium Constant', "Kohlrausch's Law of Independent Migration", "Faraday's Laws of Electrolysis", 'Conductance, Specific & Molar Conductivity Trends']
  },
  {
    id: 'chem-12',
    name: 'Chemical Kinetics',
    unit: 'Physical Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Rate Law, Rate Constant & Units', 'Order and Molecularity of Reaction', 'Integrated Rate Equations for Zero & First Order', 'Half-Life of First Order Reactions', 'Arrhenius Equation & Activation Energy (Ea)']
  },
  {
    id: 'chem-13',
    name: 'd- and f-Block Elements',
    unit: 'Inorganic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Electronic Configuration & Variable Oxidation States', 'Magnetic Properties & Spin-only Formula', 'Color of Transition Metal Ions & Catalytic Properties', 'Preparation and Properties of KMnO4 & K2Cr2O7', 'Lanthanoid Contraction and Consequences']
  },
  {
    id: 'chem-14',
    name: 'Coordination Compounds',
    unit: 'Inorganic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ["Werner's Theory of Coordination Compounds", 'IUPAC Nomenclature of Coordination Complexes', 'Isomerism: Structural & Geometrical/Optical', 'Valence Bond Theory (Inner vs Outer Orbital Complexes)', 'Crystal Field Theory (CFT), Spectrochemical Series & CFSE']
  },
  {
    id: 'chem-15',
    name: 'Haloalkanes and Haloarenes',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ['SN1 and SN2 Mechanism Comparison & Stereochemistry', 'Elimination Reactions (Saytzeff Rule)', 'Electrophilic Substitution in Haloarenes', 'Grignard Reagent Preparation & Reactions']
  },
  {
    id: 'chem-16',
    name: 'Alcohols, Phenols and Ethers',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Acidic Nature of Phenol vs Alcohols', 'Reimer-Tiemann and Kolbe Reaction', 'Lucas Test for 1°, 2°, 3° Alcohols', "Williamson's Ether Synthesis & Cleavage with HI"]
  },
  {
    id: 'chem-17',
    name: 'Aldehydes, Ketones and Carboxylic Acids',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Nucleophilic Addition Reactions (HCN, NaHSO3)', "Aldol Condensation & Cannizzaro Reaction", 'Tollens and Fehling Test Reactions', 'Acidity of Carboxylic Acids & Substituent Effects', 'Hell-Volhard-Zelinsky (HVZ) Reaction']
  },
  {
    id: 'chem-18',
    name: 'Amines (Organic Compounds Containing Nitrogen)',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Basicity of Amines in Gaseous & Aqueous Phases', "Hoffmann Bromamide Degradation", "Gabriel Phthalimide Synthesis", 'Carbylamine Test & Hinsberg Test', 'Diazonium Salts: Sandmeyer & Coupling Reactions']
  },
  {
    id: 'chem-19',
    name: 'Biomolecules',
    unit: 'Organic Chemistry',
    subject: 'Chemistry',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Carbohydrates: Monosaccharides (Glucose, Fructose structure)', 'Proteins: Amino Acids (Essential/Non-Essential), Peptide Bond', 'Primary, Secondary, Tertiary & Quaternary Protein Structure', 'Nucleic Acids: DNA vs RNA, Nucleosides & Nucleotides', 'Vitamins Classification and Deficiency Diseases']
  },

  // ================= BOTANY =================
  // Class 11
  {
    id: 'bot-1',
    name: 'The Living World & Biological Classification',
    unit: 'Diversity of Life',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Taxonomic Categories & Hierarchical System', 'Five Kingdom Classification Criteria (Whittaker)', 'Monera: Bacteria & Archaebacteria', 'Fungi: Phycomycetes, Ascomycetes, Basidiomycetes', 'Viruses, Viroids, Prions and Lichens']
  },
  {
    id: 'bot-2',
    name: 'Plant Kingdom',
    unit: 'Diversity of Life',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Algae: Chlorophyceae, Phaeophyceae, Rhodophyceae', 'Bryophytes: Liverworts and Mosses', 'Pteridophytes: Heterospory & Seed Habit Precursor', 'Gymnosperms: Conifers, Cycas, Pinus Life Cycle', 'Alternation of Generations (Haplontic, Diplontic, Haplodiplontic)']
  },
  {
    id: 'bot-3',
    name: 'Morphology and Anatomy of Flowering Plants',
    unit: 'Plant Structural Organization',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Root, Stem, Leaf Modifications', 'Inflorescence & Flower Parts (Aestivation & Placentation)', 'Fabaceae, Solanaceae, Liliaceae & New Families (Cruciferae, Malvaceae)', 'Meristematic vs Permanent Tissues (Xylem, Phloem)', 'Dicot vs Monocot Root, Stem and Leaf Anatomy']
  },
  {
    id: 'bot-4',
    name: 'Cell: The Unit of Life & Cell Cycle',
    unit: 'Cell Biology',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 5,
    completed: false,
    revisionCount: 0,
    subtopics: ['Prokaryotic vs Eukaryotic Cell Architecture', 'Fluid Mosaic Model of Plasma Membrane', 'Endomembrane System: ER, Golgi, Lysosomes, Vacuoles', 'Mitochondria & Chloroplast Semi-Autonomous Nature', 'Mitosis Stages & Checkpoints', 'Meiosis I Prophase I Sub-stages (Leptotene to Diakinesis)']
  },
  {
    id: 'bot-5',
    name: 'Photosynthesis in Higher Plants',
    unit: 'Plant Physiology',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Chloroplast Pigments & Absorption/Action Spectrum', 'Light Reaction: Non-cyclic & Cyclic Photophosphorylation', "Chemiosmotic Hypothesis (Peter Mitchell)", 'Calvin Cycle (C3 Pathway) & RuBisCO', 'C4 Pathway (Kranz Anatomy) & Photorespiration (C2)']
  },
  {
    id: 'bot-6',
    name: 'Respiration in Plants',
    unit: 'Plant Physiology',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Glycolysis (EMP Pathway) 10-step Reactions', 'Fermentation (Lactic Acid & Alcoholic)', 'Krebs Cycle (TCA Cycle) & Decarboxylations', 'Electron Transport System (ETS) & Complex I-V', 'Respiratory Quotient (RQ) for Carbohydrates, Fats, Proteins']
  },
  {
    id: 'bot-7',
    name: 'Plant Growth and Development',
    unit: 'Plant Physiology',
    subject: 'Botany',
    grade: 'Class 11',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Auxins, Gibberellins, Cytokinins physiological roles', 'Abscisic Acid (ABA) and Ethylene functions', 'Photoperiodism & Critical Photoperiod', 'Vernalization and Seed Dormancy']
  },
  // Class 12
  {
    id: 'bot-8',
    name: 'Sexual Reproduction in Flowering Plants',
    unit: 'Reproduction',
    subject: 'Botany',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Microsporogenesis & Pollen Grain Wall Layers (Sporopollenin)', 'Megasporogenesis & 7-Celled 8-Nucleate Embryo Sac', 'Pollination Mechanisms (Abiotic vs Biotic Agents)', 'Double Fertilization & Triple Fusion', 'Endosperm Development (Nuclear vs Cellular)', 'Apomixis and Polyembryony']
  },
  {
    id: 'bot-9',
    name: 'Principles of Inheritance and Variation (Mendelian Genetics)',
    unit: 'Genetics',
    subject: 'Botany',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 5,
    completed: false,
    revisionCount: 0,
    subtopics: ["Mendel's Laws (Segregation & Independent Assortment)", 'Incomplete Dominance & Co-dominance (ABO Blood Groups)', 'Chromosomal Theory of Inheritance (Sutton & Boveri)', 'Morgan Linkage and Recombination in Drosophila', 'Sex Determination Systems (XX-XY, ZZ-ZW, XO, Haplodiploidy)', 'Pedigree Analysis & Genetic Disorders (Mendelian vs Chromosomal)']
  },
  {
    id: 'bot-10',
    name: 'Molecular Basis of Inheritance',
    unit: 'Genetics',
    subject: 'Botany',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 6,
    completed: false,
    revisionCount: 0,
    subtopics: ['DNA Double Helix Structure (Watson-Crick)', "Griffith, Avery-MacLeod-McCarty, Hershey-Chase Experiments", 'Semi-conservative DNA Replication (Meselson-Stahl)', 'Transcription Machinery & RNA Polymerases in Eukaryotes', 'Genetic Code Features & Wobble Hypothesis', 'Translation Mechanism & Lac Operon Regulation', 'Human Genome Project & DNA Fingerprinting']
  },
  {
    id: 'bot-11',
    name: 'Organisms and Populations',
    unit: 'Ecology',
    subject: 'Botany',
    grade: 'Class 12',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Abiotic Factors & Adaptations in Desert Plants/Animals', 'Population Attributes (Natality, Mortality, Age Pyramids)', 'Exponential vs Logistic Growth (Verhulst-Pearl)', 'Population Interactions (Mutualism, Commensalism, Parasitism, Amensalism, Predation)']
  },
  {
    id: 'bot-12',
    name: 'Ecosystem and Biodiversity Conservation',
    unit: 'Ecology',
    subject: 'Botany',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Productivity: GPP and NPP Calculation', 'Decomposition Process Steps (Fragmentation to Mineralization)', 'Energy Flow 10% Law & Ecological Pyramids', 'Species-Area Relationship (Alexander von Humboldt)', 'The Evil Quartet Causes of Biodiversity Loss', 'In-situ vs Ex-situ Conservation Strategies']
  },

  // ================= ZOOLOGY =================
  // Class 11
  {
    id: 'zoo-1',
    name: 'Animal Kingdom',
    unit: 'Diversity of Life',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Levels of Organization, Symmetry & Coelom Types', 'Non-Chordates: Porifera to Echinodermata distinguishing characters', 'Hemichordata and Chordata Characteristics', 'Vertebrata: Cyclostomata, Chondrichthyes, Osteichthyes', 'Tetrapods: Amphibia, Reptilia, Aves, Mammalia Diagnostic Features']
  },
  {
    id: 'zoo-2',
    name: 'Structural Organization in Animals (Animal Tissues & Cockroach/Frog)',
    unit: 'Animal Structure',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Epithelial Tissue Types & Cell Junctions', 'Connective Tissue: Loose, Dense, Specialized (Bone, Cartilage, Blood)', 'Muscle Tissues: Skeletal, Smooth, Cardiac', 'Frog Morphology & Anatomy (Digestive, Respiratory, Circulatory, Excretory, Reproductive)']
  },
  {
    id: 'zoo-3',
    name: 'Biomolecules (Enzymes and Metabolic Basis)',
    unit: 'Cellular Biochemistry',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Primary & Secondary Metabolites', 'Structure of Lipids, Saturated vs Unsaturated Fatty Acids', 'Enzymes: Activation Energy, Active Site, Km Value', 'Factors Affecting Enzyme Activity (Temp, pH, Substrate conc)', 'Competitive vs Non-Competitive Enzyme Inhibition']
  },
  {
    id: 'zoo-4',
    name: 'Breathing and Exchange of Gases',
    unit: 'Human Physiology',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Respiratory Volumes & Capacities (Tidal, IRV, ERV, RV, VC, TLC)', 'Partial Pressure of O2 and CO2 at Alveoli & Tissues', 'Oxygen-Hemoglobin Dissociation Curve & Bohr Effect', 'Transport of Carbon Dioxide (Bicarbonate, Carbamino-Hb)', 'Regulation of Respiration (Medulla & Pons Centers) & Asthma/Emphysema']
  },
  {
    id: 'zoo-5',
    name: 'Body Fluids and Circulation',
    unit: 'Human Physiology',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Blood Composition, Formed Elements & ABO/Rh Incompatibility', 'Blood Clotting Cascade Factors', 'Cardiac Cycle Events, Heart Sounds & Stroke Volume', 'ECG Waves (P wave, QRS complex, T wave significance)', 'Double Circulation & Disorders (Hypertension, CAD, Angina, Heart Failure)']
  },
  {
    id: 'zoo-6',
    name: 'Excretory Products and their Elimination',
    unit: 'Human Physiology',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Nephron Structure: Cortical vs Juxtamedullary Nephrons', 'Urine Formation: Glomerular Filtration, Reabsorption, Secretion', 'Counter-Current Mechanism in Henle Loop & Vasa Recta', 'RAAS Pathway (Renin-Angiotensin-Aldosterone System)', 'ANF and ADH regulation of kidney function']
  },
  {
    id: 'zoo-7',
    name: 'Locomotion and Movement',
    unit: 'Human Physiology',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ['Skeletal Muscle Microstructure (Actin, Myosin, Sarcomere)', 'Sliding Filament Theory of Muscle Contraction & Calcium ion role', 'Human Skeleton: Axial (Skull, Vertebral Column, Ribs) & Appendicular', 'Types of Joints (Fibrous, Cartilaginous, Synovial Joints)', 'Disorders: Myasthenia Gravis, Tetany, Muscular Dystrophy, Arthritis, Gout']
  },
  {
    id: 'zoo-8',
    name: 'Neural Control and Chemical Coordination',
    unit: 'Human Physiology',
    subject: 'Zoology',
    grade: 'Class 11',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    isNtaRevised: true,
    subtopics: ['Generation & Conduction of Nerve Impulse (Resting & Action Potential)', 'Synaptic Transmission (Electrical vs Chemical Synapses)', 'Brain Regions: Cerebrum, Thalamus, Hypothalamus, Cerebellum', 'Endocrine Glands: Pituitary, Thyroid, Parathyroid, Adrenal, Pancreas Hormones', 'Mechanism of Hormone Action (Peptide vs Steroid Receptors)']
  },
  // Class 12
  {
    id: 'zoo-9',
    name: 'Human Reproduction',
    unit: 'Reproductive Biology',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Male Reproductive Anatomy & Seminiferous Tubule Histology', 'Spermatogenesis vs Oogenesis Timeline & Polar Bodies', 'Structure of Sperm & Graafian Follicle', 'Menstrual Cycle Hormonal Control (FSH, LH Surge, Estrogen, Progesterone)', 'Fertilization (Acrosome Reaction) & Blastocyst Implantation', 'Placenta Formation & Parturition (Oxytocin role)']
  },
  {
    id: 'zoo-10',
    name: 'Reproductive Health',
    unit: 'Reproductive Biology',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Moderate',
    avgQuestions: 2,
    completed: false,
    revisionCount: 0,
    subtopics: ['Contraceptive Methods (Barrier, IUDs, Hormonal Pills, Surgical)', 'Medical Termination of Pregnancy (MTP Amendment Act rules)', 'Sexually Transmitted Infections (STIs)', 'Assisted Reproductive Technologies (ART): IVF, ZIFT, GIFT, ICSI']
  },
  {
    id: 'zoo-11',
    name: 'Evolution',
    unit: 'Genetics and Evolution',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 3,
    completed: false,
    revisionCount: 0,
    subtopics: ["Miller-Urey Experiment & Chemical Evolution", 'Homologous vs Analogous Organs (Divergent vs Convergent Evolution)', 'Adaptive Radiation (Darwin Finches, Australian Marsupials)', 'Hardy-Weinberg Principle and Evolutionary Forces', 'Human Evolution Stages (Dryopithecus to Homo sapiens)']
  },
  {
    id: 'zoo-12',
    name: 'Human Health and Disease',
    unit: 'Applied Biology',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Common Pathogens: Typhoid (Widal), Pneumonia, Malaria (Plasmodium cycle)', 'Innate vs Acquired Immunity, Active vs Passive Immunity', 'Structure of Antibody Molecule (H2L2) & Humoral/Cell-Mediated', 'AIDS: HIV Replication Cycle in Macrophages & Helper T-cells', 'Cancer: Oncogenes, Contact Inhibition loss, Metastasis', 'Drug & Alcohol Abuse: Opioids, Cannabinoids, Coca Alkaloids']
  },
  {
    id: 'zoo-13',
    name: 'Biotechnology: Principles and Processes',
    unit: 'Biotechnology',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Restriction Endonucleases (Palindromic Sequences, EcoRI)', 'Cloning Vectors: pBR322 Features (ori, ampR, tetR, rop)', 'Competent Host Transformation Methods (Microinjection, Biolistics)', 'Polymerase Chain Reaction (PCR): Denaturation, Annealing, Extension', 'Bioreactors: Sparged & Stirred Tank Bioreactors & Downstream Processing']
  },
  {
    id: 'zoo-14',
    name: 'Biotechnology and its Applications',
    unit: 'Biotechnology',
    subject: 'Zoology',
    grade: 'Class 12',
    weightage: 'Very High',
    avgQuestions: 4,
    completed: false,
    revisionCount: 0,
    subtopics: ['Bt Cotton: Cry Proteins & Insect Resistance Mechanism', 'RNA Interference (RNAi) in Tobacco against Meloidegyne incognita', 'Genetically Engineered Insulin (Eli Lilly Chain A, B disulphide linkage)', 'Gene Therapy: ADA Deficiency Treatment in 4-year-old child', 'Molecular Diagnostics: ELISA & PCR', 'Transgenic Animals (Rosie cow alpha-lactalbumin) & Ethical Issues (Biopiracy)']
  }
];
